controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    position_control:
      type: forward_command_controller/ForwardCommandController

    velocity_control:
      type: forward_command_controller/ForwardCommandController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
 
    sine_controller:
      type: sine_controller/SineController

position_control:
  ros__parameters:
    joints:
      - revolute_joint
    interface_name: position
    state_interfaces:
      - position
      - velocity
      

velocity_control:
  ros__parameters:
    joints:
      - revolute_joint
    interface_name: velocity
    state_interfaces:
      - position
      - velocity

joint_trajectory_controller:
  ros__parameters:
    joints:
      - revolute_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity

sine_controller:
  ros__parameters:
    update_rate: 100
    joints:
      - revolute_joint
    state_interfaces:
      - position
      - velocity
