<?xml version="1.0"?>

<robot name="pendulum_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="width" value="0.1" />  
  <xacro:property name="height_base" value="2" />   
  <xacro:property name="height_pole" value="1" />   
  <xacro:property name="axle_offset" value="0.05" /> 
  <xacro:property name="radius" value="0.03" /> 
  <link name="world"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height_base}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height_base}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <mass value="100"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="world_to_base" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="base_link"/>
  </joint>
  
  <joint name="revolute_joint" type="revolute">
    <parent link="base_link"/>
    <child link="pole_link"/>
    <origin xyz="0.1 0 ${height_base - axle_offset}" rpy="0.1 0 0"/>
    <axis xyz="1 0 0"/>
    <limit effort="1000" velocity="1" lower="-6.28" upper="6.28"/>
  </joint>


  <link name="pole_link">
    <visual>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height_pole}" radius="${radius}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height_pole}" radius="${radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>



  <!-- ball Link -->
  <link name="ball_link">
    <visual>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="ball_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <ros2_control name="IgnitionSystem" type="system">
    <hardware>
      <plugin>ign_ros2_control/IgnitionSystem</plugin>
    </hardware>
    <joint name="revolute_joint">
      <command_interface name="position" />
      <command_interface name="velocity" />
    
      <state_interface name="position">
        <param name="initial_value">-5.0</param>
      </state_interface>
      <state_interface name="velocity"/>
      <state_interface name="effort"/>
    </joint>
  </ros2_control>

  <gazebo>
    <plugin filename="ign_ros2_control-system" name="ign_ros2_control::IgnitionROS2ControlPlugin">
      <parameters>$(find pendulum_description)/config/pendulum_controller.yaml</parameters>
    </plugin>
  </gazebo>

</robot>
