<?xml version="1.0"?>

<robot name="pendulum_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="width" value="0.1" />  
  <xacro:property name="height_base" value="2" />   
  <xacro:property name="height_pole" value="1" />   
  <xacro:property name="axle_offset" value="0.05" /> 
  <xacro:property name="radius" value="0.03" /> 

  <link name="world"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height_base}"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <geometry>
	      <box size="${width} ${width} ${height_base}"/>
      </geometry>
    </collision>
    <inertial>
      <origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      <mass value="100"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>

  <joint name="world_to_base" type="fixed">
    <origin rpy="0 0 0" xyz="0 0 0"/>
    <parent link="world"/>
    <child link="base_link"/>
  </joint>
  
  <joint name="revolute_joint" type="continuous">
    <parent link="base_link"/>
    <child link="pole_link"/>
    <origin xyz="0.1 0 ${height_base - axle_offset}" rpy="0.1 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>


  <link name="pole_link">
    <visual>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height_pole}" radius="${radius}"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <geometry>
	      <cylinder length="${height_pole}" radius="${radius}"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${height_pole/2 - axle_offset}" rpy="0 0 0"/>
      <mass value="1"/>
      <inertia
        ixx="1.0" ixy="0.0" ixz="0.0"
        iyy="1.0" iyz="0.0"
        izz="1.0"/>
    </inertial>
  </link>



  <!-- ball Link -->
  <link name="ball_link">
    <visual>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </visual>

    <collision>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>

    <inertial>
      <origin xyz="0 0 ${height_pole}" rpy="0 0 0"/>
      <mass value="0.5"/>
      <inertia
	  ixx="1.0" ixy="0.0" ixz="0.0"
	  iyy="1.0" iyz="0.0"
	  izz="1.0"/>
    </inertial>
  </link>

  <joint name="fixed_joint" type="fixed">
    <parent link="pole_link"/>
    <child link="ball_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>
</robot>
